### ISSUE TITLE
Crash on server 1.20.1

### ISSUE THREAD

**Issue by furtabs** [wendall911/SimpleTextOverlay#14]

**Comment by wendall911** [comment]
Can you provide more information? Is this for Fabric or Forge? Do you have a crash report?

**Comment by agentwolf88** [comment]
Crash at server startup.

[crash-2024-03-19_08.41.36-fml.txt](https://github.com/wendall911/SimpleTextOverlay/files/14653563/crash-2024-03-19_08.41.36-fml.txt)
