### ISSUE TITLE
Seasons out of sync with Serene Seasons

### ISSUE THREAD

**Issue by TophC7** [wendall911/SimpleTextOverlay#20]
If you configure Serene Seasons to start the world with any season but "Early Spring" the overlay doesn't reflect that and shows "early Spring" regardless of the actual season.

Also, if there's any season changes, via command or otherwise the overlay can't tell either. I understand there's no API check in the overlay hence this happens but there's also no way to fix the overlay either if the season is out of sync, rendering this feature pointless.

It would be helpful if it synced or at the very least have a way to manually fix it

**Comment by wendall911** [comment]
I'm going to test a few versions, but there is absolutely no information on what version, mod loader or anything. I do need that information, as the mod has Forge/NeoForge/Fabric and versions since 1.15 several years ago

**Comment by wendall911** [comment]
Ok, download the lastest from Curseforge or Modrinth and it is fixed. Thanks for letting me know! They changed their API again without any notification.
